repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude: \.(bat|cmd|ps1)$
  - repo: local
    hooks:
      - id: maven-spotless-check
        name: Maven Spotless Check
        entry: mvn spotless:check
        language: system
        types_or: [java, xml]
        pass_filenames: false
      - id: make-build
        name: Make Build
        entry: make build
        language: system
        pass_filenames: false
      - id: make-test
        name: Make Test
        entry: make test
        language: system
        pass_filenames: false
      - id: maven-checkstyle
        name: Maven Checkstyle
        entry: mvn checkstyle:check
        language: system
        types_or: [java]
        pass_filenames: false
      - id: make-build-wasm
        name: Make Build WASM
        entry: make build_wasm
        language: system
        pass_filenames: false
      - id: update-badges
        name: Update Badges
        entry: python3 scripts/update_badges.py
        language: system
        pass_filenames: false
      - id: swagger-2-petstore-test
        name: Swagger 2.0 Petstore Test
        entry: scripts/test_petstore.sh v2 ../petstore.json
        language: system
        pass_filenames: false
      - id: openapi-3-petstore-test
        name: OpenAPI 3.2.0 Petstore Test
        entry: scripts/test_petstore.sh v3 ../petstore_oas3.json
        language: system
        pass_filenames: false
