FROM ghcr.io/graalvm/native-image:22.3.1
RUN microdnf install -y wget tar gzip
RUN wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-20/wasi-sdk-20.0-linux.tar.gz && \
    tar -xzf wasi-sdk-20.0-linux.tar.gz && \
    mv wasi-sdk-20.0 /opt/wasi-sdk
WORKDIR /app
COPY . /app
RUN ./mvnw clean package -Pnative -DskipTests
# Note: pom.xml's native profile uses --target=wasm32-wasi and WasiSdkPath
