package cli;
import java.lang.annotation.*;

/**
 * Indicates that the annotated code was generated by the CLI.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE})
public @interface Generated {
}
